name: Deploy to GCP Cloud Run

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Docker image from GitHub Container Registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest
          docker pull $IMAGE_ID

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-app \
          --image ghcr.io/${{ github.repository }}/$IMAGE_NAME:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
