name: Deploy to GCP Cloud Run

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Authenticate to GHCR
      - name: Log into GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Pull Docker image from GHCR
      - name: Pull Docker image from GHCR
        run: |
          IMAGE_ID=ghcr.io/arcane-empires/arcane-empires/arcaneempire:latest
          docker pull $IMAGE_ID

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: 'beta'

      # Deploy to Cloud Run using the pulled image
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy arcaneempire \
          --image ghcr.io/arcane-empires/arcane-empires/arcaneempire:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated